package Geschwindigkeitsmessung;

import java.time.LocalDate;
import java.time.LocalTime;
import java.io.File;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

public class VelocityGUI extends javax.swing.JFrame {
    private VelocityTableModell model = new VelocityTableModell();
    private final JFileChooser fc = new JFileChooser();
    
    public VelocityGUI() {
        initComponents();
        
        tMeasurements.setModel(model);
        tMeasurements.setDefaultRenderer(String.class, new VelocityTableRenderer());
        fc.addChoosableFileFilter(new BinFilter());
        fc.setCurrentDirectory(new File("D:\\Schule\\3. Jahrgang 2018 - 2019\\Programmieren\\source_git\\Geschwindigkeitsmessung"));
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pMenu = new javax.swing.JPopupMenu();
        meAdd = new javax.swing.JMenuItem();
        meUpdate = new javax.swing.JMenuItem();
        meDelete = new javax.swing.JMenuItem();
        sSep = new javax.swing.JPopupMenu.Separator();
        meAvg = new javax.swing.JMenuItem();
        paMessungen = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tMeasurements = new javax.swing.JTable();
        mbBar = new javax.swing.JMenuBar();
        meDatei = new javax.swing.JMenu();
        meSpeichern = new javax.swing.JMenuItem();
        meLaden = new javax.swing.JMenuItem();

        meAdd.setText("Hinzufügen");
        meAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onAddMeasure(evt);
            }
        });
        pMenu.add(meAdd);

        meUpdate.setText("Ändern");
        meUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onUpdate(evt);
            }
        });
        pMenu.add(meUpdate);

        meDelete.setText("Löschen");
        meDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onRemove(evt);
            }
        });
        pMenu.add(meDelete);
        pMenu.add(sSep);

        meAvg.setText("Druchschnittliche Übertretung");
        meAvg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onDisplayAverage(evt);
            }
        });
        pMenu.add(meAvg);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Geschwindigkeitsmessungen");
        getContentPane().setLayout(new java.awt.GridLayout(1, 1));

        paMessungen.setBorder(javax.swing.BorderFactory.createTitledBorder("Messungen"));
        paMessungen.setLayout(new java.awt.GridLayout(1, 1));

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ScrollPaneMouseReleased(evt);
            }
        });

        tMeasurements.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tMeasurements.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tMeasurementsMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tMeasurements);

        paMessungen.add(jScrollPane1);

        getContentPane().add(paMessungen);

        meDatei.setText("Datei");

        meSpeichern.setText("Speichern");
        meSpeichern.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onSaveData(evt);
            }
        });
        meDatei.add(meSpeichern);

        meLaden.setText("Laden");
        meLaden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onLoadData(evt);
            }
        });
        meDatei.add(meLaden);

        mbBar.add(meDatei);

        setJMenuBar(mbBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onAddMeasure(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onAddMeasure
        VelocityDlg dialog = new VelocityDlg(this, true);
        dialog.setVisible(true);
        if(dialog.getIsOkay()) {
            model.add(dialog.getNewMeasurement());
        }   
    }//GEN-LAST:event_onAddMeasure

    private void tMeasurementsMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tMeasurementsMouseReleased
        if (evt.getButton() == 3) {
            this.pMenu.show(this, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_tMeasurementsMouseReleased

    private void ScrollPaneMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ScrollPaneMouseReleased
        if (evt.getButton() == 3) {
            this.pMenu.show(evt.getComponent(), evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_ScrollPaneMouseReleased

    private void onDisplayAverage(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onDisplayAverage
        JOptionPane.showMessageDialog(null, "Durchschnittliche Übertretung: " + 
                model.getAvgUeber(), "Info", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_onDisplayAverage

    private void onUpdate(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onUpdate
        int index = tMeasurements.getSelectedRow();
        if(index != -1) {
            Measurement temp = model.getMeasurement(index);
            LocalDate date = temp.getDate();
            LocalTime time = temp.getTime();
            String kennz = temp.getKennz();
            int gem = temp.getGeschw();
            int erl = temp.getErl();
            
            Measurement m = new Measurement(date, time, kennz, gem, erl);
            VelocityDlg dialog = new VelocityDlg(this, true, m);
            dialog.setVisible(true);
            
            if(dialog.getIsOkay()) {   
                Measurement mNeu = dialog.getNewMeasurement();
                model.change(index, mNeu);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Bitte zu ändernden Wert "
                    + "auswählen!", "Info", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_onUpdate

    private void onRemove(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onRemove
        int[] indices = tMeasurements.getSelectedRows();
        if(indices.length == 0) {
            JOptionPane.showMessageDialog(null, "Bitte zu löschende Werte "
                    + "auswählen!", "Info", JOptionPane.INFORMATION_MESSAGE);
        } else {
            model.delete(indices);
        }
    }//GEN-LAST:event_onRemove

    private void onSaveData(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onSaveData
        try {    
            if(fc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
                File f = fc.getSelectedFile();
                model.save(f, this.model.liste.listIterator());
            }
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, "******saveData: Fehler beim Speichern", 
                    "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();   
        }
    }//GEN-LAST:event_onSaveData

    private void onLoadData(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onLoadData
        try {
            if(fc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
                File f = fc.getSelectedFile();
                ArrayList<Measurement> ms = model.load(f);
                model.clear();
                for(Measurement m : ms) {
                    model.add(m);
                }
            } 
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, "******loadData: Fehler beim Laden", 
                    "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_onLoadData

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VelocityGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VelocityGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VelocityGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VelocityGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VelocityGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuBar mbBar;
    private javax.swing.JMenuItem meAdd;
    private javax.swing.JMenuItem meAvg;
    private javax.swing.JMenu meDatei;
    private javax.swing.JMenuItem meDelete;
    private javax.swing.JMenuItem meLaden;
    private javax.swing.JMenuItem meSpeichern;
    private javax.swing.JMenuItem meUpdate;
    private javax.swing.JPopupMenu pMenu;
    private javax.swing.JPanel paMessungen;
    private javax.swing.JPopupMenu.Separator sSep;
    private javax.swing.JTable tMeasurements;
    // End of variables declaration//GEN-END:variables
}
