package Geschwindigkeitsmessung;

import java.time.LocalDate;
import java.time.LocalTime;
import com.sun.glass.events.MouseEvent;
import javax.swing.JOptionPane;

public class VelocityGUI extends javax.swing.JFrame {
    private VelocityTableModell model = new VelocityTableModell();
    
    public VelocityGUI() {
        initComponents();
        
        tMeasurements.setModel(model);
        tMeasurements.setDefaultRenderer(Object.class, new VelocityTableRenderer());
        //model.load();
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pMenu = new javax.swing.JPopupMenu();
        meAdd = new javax.swing.JMenuItem();
        meUpdate = new javax.swing.JMenuItem();
        meDelete = new javax.swing.JMenuItem();
        sSep = new javax.swing.JPopupMenu.Separator();
        meAvg = new javax.swing.JMenuItem();
        paMessungen = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tMeasurements = new javax.swing.JTable();
        mbBar = new javax.swing.JMenuBar();
        meDatei = new javax.swing.JMenu();
        meSpeichern = new javax.swing.JMenuItem();
        meLaden = new javax.swing.JMenuItem();

        meAdd.setText("Hinzufügen");
        meAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onAddMeasure(evt);
            }
        });
        pMenu.add(meAdd);

        meUpdate.setText("Ändern");
        pMenu.add(meUpdate);

        meDelete.setText("Löschen");
        pMenu.add(meDelete);
        pMenu.add(sSep);

        meAvg.setText("Druchschnittliche Übertretung");
        meAvg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onDisplayAverage(evt);
            }
        });
        pMenu.add(meAvg);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Geschwindigkeitsmessungen");
        getContentPane().setLayout(new java.awt.GridLayout(1, 1));

        paMessungen.setBorder(javax.swing.BorderFactory.createTitledBorder("Messungen"));
        paMessungen.setLayout(new java.awt.GridLayout(1, 1));

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ScrollPaneMouseReleased(evt);
            }
        });

        tMeasurements.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tMeasurements.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tMeasurementsMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tMeasurements);

        paMessungen.add(jScrollPane1);

        getContentPane().add(paMessungen);

        meDatei.setText("Datei");

        meSpeichern.setText("Speichern");
        meDatei.add(meSpeichern);

        meLaden.setText("Laden");
        meDatei.add(meLaden);

        mbBar.add(meDatei);

        setJMenuBar(mbBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onAddMeasure(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onAddMeasure
        VelocityDlg dialog = new VelocityDlg(this, true);
        dialog.setVisible(true);
        if(dialog.getIsOkay()) {
            model.add(dialog.getNewMeasurement());
        }
    }//GEN-LAST:event_onAddMeasure

    private void tMeasurementsMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tMeasurementsMouseReleased
        if (evt.getButton() == 3) {
            this.pMenu.show(this, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_tMeasurementsMouseReleased

    private void ScrollPaneMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ScrollPaneMouseReleased
        if (evt.getButton() == 3) {
            this.pMenu.show(evt.getComponent(), evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_ScrollPaneMouseReleased

    private void onDisplayAverage(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onDisplayAverage
        JOptionPane.showMessageDialog(null, "Durchschnittliche Übertretung: " + 
                model.getAvgUeber(), "Info", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_onDisplayAverage

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VelocityGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VelocityGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VelocityGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VelocityGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VelocityGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuBar mbBar;
    private javax.swing.JMenuItem meAdd;
    private javax.swing.JMenuItem meAvg;
    private javax.swing.JMenu meDatei;
    private javax.swing.JMenuItem meDelete;
    private javax.swing.JMenuItem meLaden;
    private javax.swing.JMenuItem meSpeichern;
    private javax.swing.JMenuItem meUpdate;
    private javax.swing.JPopupMenu pMenu;
    private javax.swing.JPanel paMessungen;
    private javax.swing.JPopupMenu.Separator sSep;
    private javax.swing.JTable tMeasurements;
    // End of variables declaration//GEN-END:variables
}
